# Generated by Django 4.1.3 on 2024-08-30 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_alter_productdownload_options'),
        ('localize', '0003_rename_sign_possition_currency_sign_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(editable=False, max_length=16, unique=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localize.currency')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255)),
                ('product_sku', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='carts.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_option_title', models.CharField(max_length=255)),
                ('price_change_type', models.CharField(choices=[('reduce', 'Reduce'), ('increase', 'Increase'), ('replace', 'Replace')], max_length=10)),
                ('price_change_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attribute_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productattributeoption')),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='carts.cartproduct')),
            ],
        ),
    ]
