# Generated by Django 4.1.3 on 2023-12-13 12:26

from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_infopage_mainpage_page_content_page_content_bg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[utils.validators.video_validator]),
        ),
    ]
