# Generated by Django 4.1.3 on 2024-09-02 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0003_remove_state_region_state_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_always_applied', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_groups', to='geo.country')),
            ],
        ),
    ]
