# Generated by Django 4.1.3 on 2024-09-09 13:46

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('provider', models.CharField(choices=[('bank', 'Bank Transfer'), ('cod', 'Cash on Delivery'), ('paypal', 'PayPal')], default='bank', max_length=32)),
                ('description', models.CharField(max_length=1024)),
                ('instructions', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='payment_methods_icons', validators=[utils.validators.image_validator])),
                ('is_active', models.BooleanField(default=True)),
                ('order_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderstatus')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
        ),
    ]
