# Generated by Django 4.1.3 on 2023-11-28 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('code', models.CharField(max_length=6, unique=True)),
                ('discount_type', models.CharField(choices=[('amount', 'Amount'), ('percent', 'Percent')], default='amount', max_length=7)),
                ('discount_value', models.PositiveIntegerField()),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('allowed_brands', models.ManyToManyField(blank=True, related_name='discount_codes', to='catalog.brand')),
                ('allowed_categories', models.ManyToManyField(blank=True, related_name='discount_codes', to='catalog.productcategory')),
                ('allowed_products', models.ManyToManyField(blank=True, related_name='discount_codes', to='catalog.product')),
                ('allowed_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_codes', to=settings.AUTH_USER_MODEL)),
                ('used_for_orders', models.ManyToManyField(blank=True, related_name='discount_codes', to='catalog.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
