# Generated by Django 4.1.3 on 2023-11-29 11:48

import django.db.models.deletion
from django.db import migrations, models

import common.models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_discountcode_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', common.models.TinifiedImageField(blank=True, null=True, upload_to='products_images', validators=[utils.validators.image_validator])),
                ('video', models.FileField(blank=True, null=True, upload_to='products_videos', validators=[utils.validators.video_validator])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='catalog.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
