# Generated by Django 4.1.3 on 2023-12-13 12:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='file',
            field=models.FileField(upload_to='products_documents', validators=[utils.validators.document_validator]),
        ),
        migrations.CreateModel(
            name='ProductDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to='products_downloads', validators=[utils.validators.dowload_file_validator])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='catalog.product')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
