# Generated by Django 4.1.3 on 2023-12-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_promotion_created_at_promotion_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdownload',
            options={'ordering': ['id']},
        ),
    ]
