# Generated by Django 4.1.3 on 2024-09-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_taxgroup_created_at_taxgroup_deleted_at_and_more'),
        ('catalog', '0008_alter_productdownload_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_groups',
            field=models.ManyToManyField(blank=True, related_name='products', to='taxes.taxgroup'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='tax_groups',
            field=models.ManyToManyField(blank=True, related_name='categories', to='taxes.taxgroup'),
        ),
    ]
