# Generated by Django 4.1.3 on 2024-09-09 14:14

from django.db import migrations, models

import common.models
import utils.functions
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_tax_groups_productcategory_tax_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdocument',
            name='file',
            field=models.FileField(upload_to=utils.functions.get_upload_path, validators=[utils.validators.document_validator]),
        ),
        migrations.AlterField(
            model_name='productdownload',
            name='file',
            field=models.FileField(upload_to=utils.functions.get_upload_path, validators=[utils.validators.download_file_validator]),
        ),
        migrations.AlterField(
            model_name='productmultimedia',
            name='image',
            field=common.models.TinifiedImageField(blank=True, null=True, upload_to=utils.functions.get_upload_path, validators=[utils.validators.image_validator]),
        ),
        migrations.AlterField(
            model_name='productmultimedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.functions.get_upload_path, validators=[utils.validators.video_validator]),
        ),
    ]
