# Generated by Django 4.1.3 on 2023-12-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['id'], 'verbose_name_plural': 'Countries'},
        ),
    ]
