# Generated by Django 4.1.3 on 2024-01-08 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_country_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='region',
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='geo.country'),
            preserve_default=False,
        ),
    ]
