# Generated by Django 4.1.3 on 2024-09-02 15:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('provider', models.CharField(choices=[('standard', 'Standard'), ('econt', 'Econt'), ('speedy', 'Speedy')], default='standard', max_length=32)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ship_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_ship_over', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
