# Generated by Django 4.1.3 on 2023-12-14 10:11

import django.db.models.deletion
from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=32)),
                ('title_en', models.CharField(max_length=32, null=True)),
                ('title_bg', models.CharField(max_length=32, null=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('sign', models.CharField(max_length=8, unique=True)),
                ('sign_possition', models.CharField(choices=[('before_price', 'Before price'), ('after_price', 'After price')], default='before_price', max_length=32)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=32)),
                ('title_en', models.CharField(max_length=32, null=True)),
                ('title_bg', models.CharField(max_length=32, null=True)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='languages_icons', validators=[utils.validators.image_validator])),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.FloatField()),
                ('currency_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='localize.currency')),
                ('currency_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='localize.currency')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
