# Generated by Django 4.1.3 on 2024-02-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localize', '0002_alter_currency_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='sign_possition',
            new_name='sign_position',
        ),
    ]
