# Generated by Django 4.1.3 on 2023-12-14 14:14

import django.db.models.deletion
from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localize', '0002_alter_currency_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('title_en', models.CharField(max_length=128, null=True)),
                ('title_bg', models.CharField(max_length=128, null=True)),
                ('domain', models.CharField(max_length=128, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores_logos', validators=[utils.validators.image_validator])),
                ('default_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='localize.currency')),
                ('default_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='localize.language')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
