# Generated by Django 4.1.3 on 2023-12-14 14:46

import django.db.models.deletion
from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_country_options'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='City')),
                ('city_en', models.CharField(blank=True, max_length=64, null=True, verbose_name='City')),
                ('city_bg', models.CharField(blank=True, max_length=64, null=True, verbose_name='City')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('title_en', models.CharField(max_length=128, null=True, verbose_name='Title')),
                ('title_bg', models.CharField(max_length=128, null=True, verbose_name='Title')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='Address')),
                ('address_en', models.CharField(blank=True, max_length=128, null=True, verbose_name='Address')),
                ('address_bg', models.CharField(blank=True, max_length=128, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Phone')),
                ('phone_en', models.CharField(blank=True, max_length=64, null=True, verbose_name='Phone')),
                ('phone_bg', models.CharField(blank=True, max_length=64, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=64, verbose_name='Email')),
                ('email_en', models.EmailField(blank=True, max_length=64, null=True, verbose_name='Email')),
                ('email_bg', models.EmailField(blank=True, max_length=64, null=True, verbose_name='Email')),
                ('gps_latitude', models.FloatField(blank=True, null=True, verbose_name='GPS Latitude')),
                ('gps_longitude', models.FloatField(blank=True, null=True, verbose_name='GPS Longitude')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stores_locations_images', validators=[utils.validators.image_validator])),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.state')),
            ],
            options={
                'verbose_name': 'Store Location',
                'verbose_name_plural': 'Store Locations',
                'ordering': ['id'],
            },
        ),
    ]
