# Generated by Django 4.1.3 on 2024-09-09 14:14

from django.db import migrations, models

import utils.functions
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_storelocation_created_at_storelocation_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.functions.get_upload_path, validators=[utils.validators.image_validator]),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.functions.get_upload_path, validators=[utils.validators.image_validator]),
        ),
    ]
