# Generated by Django 4.1.3 on 2024-09-09 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0001_initial'),
        ('payments_methods', '0002_alter_paymentmethod_image'),
        ('accounts', '0003_userreview'),
        ('localize', '0004_alter_language_icon'),
        ('shipping_methods', '0001_initial'),
        ('geo', '0003_remove_state_region_state_country'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=128)),
                ('user_agent', models.CharField(max_length=1024)),
                ('is_invoice_requested', models.BooleanField(default=False)),
                ('customer_first_name', models.CharField(max_length=64)),
                ('customer_last_name', models.CharField(max_length=64)),
                ('customer_phone', models.CharField(max_length=64)),
                ('customer_email', models.EmailField(max_length=64)),
                ('customer_company_name', models.CharField(blank=True, max_length=128)),
                ('customer_company_number', models.CharField(blank=True, max_length=128)),
                ('customer_invoice_details', models.CharField(blank=True, max_length=128)),
                ('billing_address_first_name', models.CharField(blank=True, max_length=128)),
                ('billing_address_last_name', models.CharField(blank=True, max_length=128)),
                ('billing_address_country_title', models.CharField(blank=True, max_length=128)),
                ('billing_address_city', models.CharField(blank=True, max_length=128)),
                ('billing_address_street', models.CharField(blank=True, max_length=128)),
                ('billing_address_phone', models.CharField(blank=True, max_length=128)),
                ('billing_address_email', models.EmailField(blank=True, max_length=128)),
                ('billing_address_notes', models.TextField(blank=True)),
                ('shipping_address_first_name', models.CharField(blank=True, max_length=128)),
                ('shipping_address_last_name', models.CharField(blank=True, max_length=128)),
                ('shipping_address_country_title', models.CharField(blank=True, max_length=128)),
                ('shipping_address_city', models.CharField(blank=True, max_length=128)),
                ('shipping_address_street', models.CharField(blank=True, max_length=128)),
                ('shipping_address_phone', models.CharField(blank=True, max_length=128)),
                ('shipping_address_email', models.EmailField(blank=True, max_length=128)),
                ('shipping_address_notes', models.TextField(blank=True)),
                ('payment_method_provider', models.CharField(blank=True, max_length=32)),
                ('payment_method_title', models.CharField(blank=True, max_length=128)),
                ('shipping_method_provider', models.CharField(blank=True, max_length=32)),
                ('shipping_method_title', models.CharField(blank=True, max_length=128)),
                ('shipping_method_track_number', models.CharField(blank=True, max_length=128)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='accounts.useraddress')),
                ('billing_address_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_country', to='geo.country')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carts.cart')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='localize.currency')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments_methods.paymentmethod')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='accounts.useraddress')),
                ('shipping_address_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_country', to='geo.country')),
                ('shipping_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping_methods.shippingmethod')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderstatus')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
