# Generated by Django 4.1.3 on 2024-09-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
