# Generated by Django 4.1.3 on 2024-09-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_taxgroup_created_at_taxgroup_deleted_at_and_more'),
        ('orders', '0004_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='tax_groups',
            field=models.ManyToManyField(related_name='order_products', to='taxes.taxgroup'),
        ),
    ]
