# Generated by Django 4.1.3 on 2024-09-10 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_methods', '0002_alter_paymentmethod_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_alter_orderproduct_tax_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('subtotal', 'Subtotal'), ('tax', 'Tax'), ('shipping', 'Shipping'), ('discount', 'Discount'), ('total', 'Total')], default='subtotal', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_totals', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Total',
                'verbose_name_plural': 'Order Totals',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField()),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='orders.order')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='orders.orderstatus')),
            ],
            options={
                'verbose_name': 'Order Status Change',
                'verbose_name_plural': 'Order Status Changes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=512)),
                ('expiration_date_time', models.DateTimeField(blank=True, null=True)),
                ('transaction_date_time', models.DateTimeField(blank=True, null=True)),
                ('transaction_number', models.CharField(blank=True, max_length=128)),
                ('transaction_error', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('fail', 'Fail')], default='pending', max_length=7)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_quotes', to='orders.order')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_quotes', to='payments_methods.paymentmethod')),
            ],
            options={
                'verbose_name': 'Order Quote',
                'verbose_name_plural': 'Order Quotes',
            },
        ),
    ]
