name: CI/CD Workflow

on:
    push:
        branches: ['**']
    pull_request:
        branches: ['main']

jobs:
    test-and-lint:
        name: Test and Lint
        runs-on: ubuntu-latest
        if: github.ref != 'refs/heads/main'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.9'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Set environment variables
              run: |
                  echo "SECRET_KEY=${{ secrets.SECRET_KEY }}"
                  echo "CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}"
                  echo "CSRF_TRUSTED_ORIGINS=${{ secrets.CSRF_TRUSTED_ORIGINS }}"
                  echo "DATABASE_URL=${{ secrets.DATABASE_URL }}"
                  echo "TEST_DATABASE_URL=${{ secrets.TEST_DATABASE_URL }}"

            - name: Run linting
              run: flake8

            - name: Run tests
              run: python manage.py test

    deploy:
        name: Deploy to Server
        runs-on: ubuntu-latest
        needs: test-and-lint
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Executing remote SSH commands using SSH key
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_PRIV_KEY }}
                  port: ${{ secrets.PORT }}
                  script: cd ~/online_store_be && bash pull_restart.sh
