name: remote ssh command
on:
    push:
        branches:
            - main
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using ssh key
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_PRIV_KEY }}
                  port: ${{ secrets.PORT }}
                  script: cd ~/online_store_be && bash pull_restart.sh
